workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
      cancel_previous_builds: false
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.numforlife.com
      vars:
        APP_STORE_APPLE_ID: 184232456@qq.com
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up debug log
        script: |
          set -e
          set -x
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - 184232456@qq.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
